fixtures:
  repositories:
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt.git
      tag: v10.0.1
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
